spring:
  #Database settings
  datasource:
    url: jdbc:postgresql://localhost:5432/EzJob
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: jugler228@gmail.com
    password: fmbeholhkhmqvukr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6380
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
#    hibernate:
#        ddl-auto: create

  security:
    #Secret used for signing JWT token.
    secret: gms
    #Validity time of JWT token in milliseconds.
    expirationTime: 36000000

server:
  servlet:
    context-path: /api
  port: 8080
