spring:
  #Database settings
  datasource:
    url: jdbc:postgresql://localhost:5432/EzJob
    username: postgres
    password: Mymein2003
    driver-class-name: org.postgresql.Driver

  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

  security:
    # Secret used for signing JWT token.
    secret: gms
    #Validity time of JWT token in milliseconds.
    expirationTime: 36000000

server:
  port: 8080
