spring:
  #Database settings
  datasource:
    url: jdbc:postgresql://localhost:5432/EzJob
    username: postgres
    password: Mymein2003
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6380
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
#    hibernate:
#      ddl-auto: create

  security:
    #Secret used for signing JWT token.
    secret: gms
    #Validity time of JWT token in milliseconds.
    expirationTime: 36000000

server:
  port: 8080
