spring:
  #Database settings
  datasource:
    url: jdbc:postgresql://localhost:5432/EzJob
    username: postgres
    password: Mymein2003
    driver-class-name: org.postgresql.Driver

  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

server:
  port: 8080
